### ISSUE TITLE
Get Uid from PresentTags

### ISSUE THREAD

**Issue by TheBlubb14** [Ellerbach/LegoDimensions#17]
Hi,
thanks for this awesome library.

Is there a chance I could get the cards uid from the `PresentTags`?

I am using the uid as an identifier for the tags, as the ones I have cannot be read through `ReadTag`

**Comment by Ellerbach** [comment]
That should be doable. I would greatly appreciate a PR for this ;-)

It's about adding the byte[] in the class and adding it here: https://github.com/Ellerbach/LegoDimensions/blob/ce93166e54394cea51894b9a345dd323cfc047ec/LegoDimensions/LegoPortal.cs#L474

I think it's about it! And testing all this!

**Comment by Ellerbach** [comment]
And thanks for the PR as well! The new release is available.
